version: 2.1
aliases:
  - &parameters
    buildx_url:
      default: https://github.com/docker/buildx/releases
      type: string
    buildx_version:
      default: 0.5.1
      type: string
    platforms:
      default: linux/amd64
      type: string
    version:
      default: dind
      type: string
    repo:
      default: drpsychick
      type: string
    tag:
      default: dind
      type: string
  - &docker-dind
    - image: docker:dind
  - &build
    - checkout
    - setup_remote_docker:
        version: 20.10.2
    - run:
        name: Install buildx
        command: |
          apk add --no-cache curl
          mkdir -p ~/.docker/cli-plugins
          fileName="buildx-v<< parameters.buildx_version >>.linux-amd64"
          url="<< parameters.buildx_url >>/download/v<< parameters.buildx_version >>/${fileName}"
          curl -sSL -o ~/.docker/cli-plugins/docker-buildx $url
          chmod a+x ~/.docker/cli-plugins/docker-buildx
          docker buildx install
    - run:
        name: Bootstrap buildx
        command: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker context create xbuilder
          docker buildx create xbuilder --name xbuilder --use
          docker buildx inspect --bootstrap
    - run:
        name: Build images
        command: |
          cd images
          for img in $(ls -1d *); do
            echo "Building << parameters.repo >>/$img:<< parameters.tag >>"
            docker buildx build --progress plain --platform << parameters.platforms >> \
              --build-arg VERSION=<< parameters.version >> \
              --build-arg BUILDX_VERSION=<< parameters.buildx_version >> \
              -t << parameters.repo >>/$img:<< parameters.tag >> .
          done

jobs:
  build-latest:
    parameters: *parameters
    docker: *docker-dind
    resource_class: small
    steps: *build
  build-20-dind:
    parameters: *parameters
    docker: *docker-dind
    resource_class: small
    steps: *build

workflows:
  version: 2
  chart-test:
    jobs:
      - build-latest
      - build-20-dind:
          matrix:
            parameters:
              buildx_version: ["0.5.0"]
