version: 2.1
aliases:
  - &parameters
    buildx_url:
      default: https://github.com/docker/buildx/releases
      type: string
    buildx_version:
      default: 0.5.1
      type: string
  - &docker-dind
    - image: docker:dind
  - &build
    - checkout
    - run:
        name: Install buildx
        command: |
          apk add --no-cache curl
          export BUILDX_URL=<< parameters.buildx_url >>
          export BUILDX_VERSION=<< parameters.buildx_version >>
          mkdir -p ~/.docker/cli-plugins
          fileName="buildx-v${BUILDX_VERSION}.linux-${BUILDX_ARCH}"
          url="${BUILDX_URL}/download/v${BUILDX_VERSION}/${fileName}"
          curl -sSL -o ~/.docker/cli-plugins/docker-buildx $url
          chmod a+x ~/.docker/cli-plugins/docker-buildx
          docker buildx install
          echo 'export DOCKER_CLI_EXPERIMENTAL="enabled"' >> $BASH_ENV
          echo 'export DOCKER_BUILDKIT=1' >> $BASH_ENV
    - setup_remote_docker:
        version: 20.10.2
    - run:
        name: Bootstrap buildx
        command: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker context create xbuilder
          docker buildx create xbuilder --name xbuilder --use
          docker buildx inspect --bootstrap
    - run:
        name: Build images
        command: |
          export BUILDX_VERSION=<< parameters.buildx_version >>
          echo "$DOCKER_CLI_EXPERIMENTAL - $DOCKER_BUILDKIT"
          echo "$VERSION - $BUILDX_VERSION"
          cd images
          for img in $(ls -1d *); do
            docker buildx build --progress plain --platform $PLATFORMS --build-arg VERSION=$VERSION \
              --build-arg BUILDX_VERSION=$BUILDX_VERSION \
              -t $REPO/$img:$TAG --load .
          done

jobs:
  build-latest:
    parameters: *parameters
    environment:
      BUILDX_ARCH: amd64
      PLATFORMS: linux/amd64,linux/arm64
      VERSION: dind
      REPO: drpsychick
      TAG: latest
    docker: *docker-dind
    resource_class: small
    steps: *build
  build-20-dind:
    environment:
      BUILDX_URL: https://github.com/docker/buildx/releases
      BUILDX_VERSION: 0.5.1
      BUILDX_ARCH: amd64
      PLATFORMS: linux/amd64
      VERSION: 20-dind
      REPO: drpsychick
      TAG: 20-dind
    docker: *docker-dind
    resource_class: small
    steps: *build

workflows:
  version: 2
  chart-test:
    jobs:
      - build-latest
      - build-20-dind:
          matrix:
            parameters:
              buildx_version: ["0.5.0"]
